#!/bin/bash

#SBATCH --partition=defq
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=8
#SBATCH --mem=100g
#SBATCH --time=24:00:00
#SBATCH --job-name=quast
#SBATCH --output=/share/BioinfMSc/Bill_resources/Tbrucei/fastq/Group4/logs/slurm-%x-%j.out
#SBATCH --error=/share/BioinfMSc/Bill_resources/Tbrucei/fastq/Group4/logs/slurm-%x-%j.err
#SBATCH --mail-type=ALL
#SBATCH --mail-user=pcytm7@exmail.nottingham.ac.uk


source $HOME/.bash_profile

conda activate Tom

cd /share/BioinfMSc/Bill_resources/Tbrucei/fastq/Group4

fastqc --fastqc In_vitro*.fastq.gz -o /share/BioinfMSc/Bill_resources/Tbrucei/fastq/Group4

conda deactivate
